### ISSUE TITLE
Symfony 3 compliance

### ISSUE THREAD

**Issue by Caroga** [matks/MarkdownBlogBundle#5]
I was wondering if this will get updated to work with SF3 as well? 
As https://github.com/matks/MarkdownBlogBundle/issues/4 states that given dependency is unnecessary it might be a good idea to remove it and try this out on SF3?

**Comment by matks** [comment]
@Caroga Nice suggestion ! Indeed removing the sf2.8 dependency and a few fixes make the Bundle sf3-compatible. This was done in https://github.com/matks/MarkdownBlogBundle/pull/6 .

This patch has been packaged in [v1.0.1](https://github.com/matks/MarkdownBlogBundle/tree/1.0.1) so once [packagist](https://packagist.org/packages/matks/markdown-blog-bundle) is up-to-date you should be able to use MarkdownBlogBundle with sf `>=3.1` . sf `3.0` might work but in [this example](https://github.com/matks/markdown-blog-bundle-example) I had issues with Twig versions.

**Comment by Caroga** [comment]
Hi, thanks for providing feedback. I will try this out next week. I'll report back with any findings I might have.
Thank you
